// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_X-FnmF-AAbXYvlKc2ZaIQ3hvmHAdAU',
    appId: '1:253734409786:web:806b55eb581e3400f6c703',
    messagingSenderId: '253734409786',
    projectId: 'todolist-255f0',
    authDomain: 'todolist-255f0.firebaseapp.com',
    storageBucket: 'todolist-255f0.appspot.com',
    measurementId: 'G-2J303WCJ55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4V3KmR28BqyUYub7PKuOQ-CIE4hc7D6Y',
    appId: '1:253734409786:android:f27816ae910620b2f6c703',
    messagingSenderId: '253734409786',
    projectId: 'todolist-255f0',
    storageBucket: 'todolist-255f0.appspot.com',
  );
}
